### ISSUE TITLE
failure to install

### ISSUE THREAD

**Issue by bsxfan** [quinnj/Sublime-Julia#2]
Hi @karbarcca 

Thanks for making your sublime package available. Could you perhaps help me with installation on my windows 7 machine.
- I have never used sublime before, but I have just installed version 2.
- I followed the instruction in your readme. I seem to have succesfully installed the package control and to have cloned sublime-julia from github to what I believe is the correct location on my computer.

When I go to view -> syntax, I find Julia, but I do not see sublime-julia. Restarting sublime does not help. Do you have any suggestions?

Thanks

**Comment by quinnj** [comment]
First off, welcome to Sublime! I'm a relatively new user myself (just a few months ago), but after trying out 6-8 different text editors, I'm convinced Sublime is the most powerful/extendable and easy to use. If you're interested, I'd recommend going through the Nettuts+ Sublime tutorials. It's a series of 5-10 minute videos (probably an hour or two total), but I think it's a great crash course to discovering some of the more powerful features of Sublime. [Link](http://net.tutsplus.com/articles/news/perfect-workflow-in-sublime-text-free-course/)

For your install problem, did you already install the "Julia" package from Package Control? (ctrl+shift+p, "Install Package", "Julia") If so, then that will conflict with the Sublime-Julia package. The "Julia" package is just a simple syntax file which is already included in Sublime-Julia, so I would remove the "Julia" package (ctrl+shift+p, "Remove Package", "Julia"). After that (or if you didn't install the Julia package in the first place), then going to Syntax -> Julia will be the Sublime-Julia file (the syntax files are named for the language, not the package).

Were you able to get the REPL up and running?

**Comment by bsxfan** [comment]
- Thanks for the video links!
- No I didn't install any other Julia package. When I list packages, I see just two: "Package Control" and "Sublime-Julia".
- I tried again. I uninstalled Sublime-Julia and unstalled again. Same problem.

**Comment by quinnj** [comment]
What exactly is the problem you're seeing? Is syntax high-lighting not working? The REPL not working?

**Comment by bsxfan** [comment]
After having installed your package, I tried to follow your instruction:
'To explicitly use this syntax, navigate to Julia REPL or .jl file and navigate the menus "View -> Syntax -> Sublime-Julia -> Julia" '. But the only option I find is "View -> Syntax -> Julia". If I do that, I get a nice-looking syntax highlighting, but I suspect that is not the one provided by your package, or is it? How can I check this?

**Comment by quinnj** [comment]
Good catch. I need to update the documentation. Going Syntax -> Julia is indeed the correct language sytnax provided by my package. I'll update.

**Comment by bsxfan** [comment]
OK, great thanks. 

Next, the REPL: Is the REPL lanched by Sublime the (rather old) windows binary supplied by the Julia folks for download? If so, then I won't use it now. Many bugs have been fixed since and I need to be working with a new build of Julia almost daily. (We cross-compile Julia builds on a Linux machine.)  Or can I launch my new Julia builds out of Sublime?

**Comment by quinnj** [comment]
The only requirement is that you run the julia-release-basic.exe file instead of julia-release-readline.exe to launch the REPL. I cross-compile my Julia build and point to the julia-basic.bat file in my cross-compiled build in the Sublime-Julia settings environment.

**Comment by bsxfan** [comment]
OK, so I seem to have managed to point the various paths in the sublime-julia settings to my Julia executables and I manage to get some action:
- If I do a build (ctrl-B), then it launches my current file into some version of the repl running in the sublime console. It does not:
  -- dislay the banner (which is good)
  -- run my .juliarc.jl 
  -- show any error output
  -- succesfully read from STDIN
- Under Tools -> SublimeREPL-Julia, there are 7 options. 
  -- If I understand correctly one has to open the REPL first by calling the last option "Julia". (This REPL opens with .juliarc.jl and a banner and seems to behave w.r.t. basic input and output.) 
  -- After having done that, I can then make various things happen by trying the other six options, but I don't understand the differences between "send to REPL" and "eval in REPL". I also don't understand what "lines" does.

**Comment by bsxfan** [comment]
I have another question:

I see that autocomplete sees all julia keywords, but it sees only my new identifiers in the file I am busy editing---it does not see my identifiers delared in my other julia source files in the same project. Would it be possible to extend the autocomplete to harvest identifiers from the whole project?

**Comment by quinnj** [comment]
- For the "Build system" (i.e. ctrl+b), this is normal sublime behavior. It is meant to build and execute files, literally it's doing `julia.bat filename` from the command line console. That said, you could certainly create a new build system (Tools -> Build System -> New Build System (at the very bottom)) to fit your needs (redirect STDERR, run .juliarc.jl, etc.). I'm not an expert on build systems, but there's quite a bit of documentation out there on how to tweak them (see [here](http://docs.sublimetext.info/en/latest/file_processing/build_systems.html)).
- Yep, first open up the Julia repl (which should behave similarly to running julia.bat from the command line). "Transfer to REPL" does just that, it transfers either the text you have selected ("Selection"), the entire line or lines you're on/selected ("Lines"), or transfer the entire file in the REPL ("File"); though nothing is "run" (evaluated in the REPL). For that, use "Eval in REPL" which will transfer the text to the REPL, but also submit (i.e. like pressing 'enter') so the code is actually run/evaluated. Note that these commands only work from a valid julia file (file extension .jl), this is so they don't conflict with other commands that may be set up for different languages/files. Honestly, I never use the "Tools -> SublimeREPL-Julia" menu because I prefer the shortcut keys. `ctrl+enter` will evaluate the currently selected text (or entire line if nothing is selected) in the REPL and I set up `ctrl+j` to open my REPL, which is basically everything the menu does. Take a look at the `Sublime User Key Bindings.txt` file in the Sublime-Julia folder to see my `ctrl+j` shortcut.

**Comment by quinnj** [comment]
re: the autocomplete question--

This isn't something I've researched a ton. The current auto-complete is just built in to Sublime, I didn't handcraft anything. There are ways to expand it, but I haven't looked into it much. I did come across this [SO question](http://stackoverflow.com/questions/16144443/sublime-text-adding-symbols-to-a-new-language-definition-syntax-highlighting) that is related though, so that's probably a good place to start. I'll open a new issue for this to dig into this more.

**Comment by quinnj** [comment]
@bsxfan, let me know if you have any questions, otherwise I'll close this.

**Comment by bsxfan** [comment]
Thanks, @karbarcca. Yes, your Julia package is indeed installed succesfully in my editor and is working very well, apart from some very minor issues. Thanks again for intruducing me to Sublime and thanks for making your package available. It is already making a huge difference to my productivity!
